# Numpy的数组和原生python的性能对比

In [2]:
import random
import time
import numpy as np

a=[]
#随机1亿个数据
for i in range(100000000):
    a.append(random.random())
print('随机完毕')

随机完毕


In [3]:
# 转换为ndarray
b = np.array(a)
print('转换完毕')

转换完毕


In [4]:
# ndarray与Python原生list运算效率对比
# 记录 sum(a) 开始执行时的时间
t1 = time.time()
# 用python的内置函数sum()计算列表a中所有元素的总和
sum1 = sum(a)
# 记录 sum(a) 执行结束时的时间
t2 = time.time()
# 记录 np.sum(b) 开始执行时的时间
t4 = time.time()
# 使用numpy的np.sum()函数计算数组b中所有元素的总和
sum3 = np.sum(b)
# 记录 np.sum(b) 执行结束时的时间
t5 = time.time()
print(t2 - t1, t5 - t4)

0.7771909236907959 0.10548806190490723


# 常用操作

In [5]:
# 一维数组
list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))
oneArray = np.array(list1)
print(type(oneArray))
print(oneArray)

[1, 2, 3, 4]
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]


In [7]:
# 二维数组
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)
print(list2)
twoArray.tolist()

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


[[1, 2], [3, 4], [5, 6]]

In [8]:
# 常用属性
#看ndarray的各种属性
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像) 
print(twoArray.ndim)

# 形状（行，列） (0 axis,1 axis)
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)
# 数据类型
print(twoArray.dtype)

2
(3, 2)
6
int64


# 调整数组形状

In [12]:
arr =np.array([[1,2,3],[4,5,6]])
print(arr)
arr1=arr
print(id(arr1))

[[1 2 3]
 [4 5 6]]
2513220012144


In [13]:
# 改变形状
arr.shape=(3,2)
print(id(arr))
print(id(arr1))
print(arr)

2513220012144
2513220012144
[[1 2]
 [3 4]
 [5 6]]


In [14]:
# 返回一个新的数组，reshape后id和之前的不一样
arr2 = arr.reshape(2,3)
print(arr)
print(id(arr))
print(id(arr2))
arr2

[[1 2]
 [3 4]
 [5 6]]
2513220012144
2513220010992


array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 将多维变成一维数组
# 一维数组长度为6  C表示行优先展开
arr3 =arr.reshape((6,),order = 'C')
# 展开成一维数组
arr4 = arr.flatten()
print(arr3)
print('-' * 50)
print(arr4)

[1 2 3 4 5 6]
--------------------------------------------------
[1 2 3 4 5 6]


In [17]:
# 转成三维
#最前面的是零轴，轴越小，越靠外，最小的轴是最外层
# 0轴，1轴，2轴
t = np.arange(24)
# 第一维包含2个块  第二维每块中有3行  第三维每行中有4个元素
t2 = t.reshape((2, 3, 4))
print(t2)
print(t2.shape)
print(t2.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [19]:
# 变为四维   第一维包含2个块  第二维每块中有3块  第三维每块中有2行  第四维每行中有2个元素
t3 = t.reshape((2, 3, 2, 2))
print(t3)
print(t3.shape)
print(t3.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4


In [20]:
#将数组转换为列表 tolist
a = np.array([9, 12, 88, 14, 25])
print(type(a))
list_a = a.tolist()
print(list_a)
print(type(list_a))

<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


# numpy的数据类型

In [21]:
import random

f = np.array([1, 2, 3, 4, 127], dtype=np.int8)  # 返回数组中每个元素的字节单位长度,dtype设置数据类型
print(f.itemsize)  # 1 np.int16(一个字节)
# 获取数据类型
print(f.dtype)

1
int8


In [22]:
# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)
print(f1.itemsize)  #显示字节数

int64
8


In [23]:
random.random()  # 随机生成0-1之间的小数

0.8652402519571599

In [24]:
# 数组和数的计算
# 由于numpy的广播机机制在运算过程中，加减乘除的值被广播到所有的元素上面
#无论多少维的ndarray都可以直接和一个常数进行运算
# 不能对列表进行直接加整数操作
t1 = np.arange(24).reshape((6, 4))
print(t1)
print("-" * 20)
print(t1 + 2)
print("-" * 20)
print(t1 * 2)
print("-" * 20)
print(t1 / 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [26]:
#形状相同,才可以进行加减乘除
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
print('-' * 50)
print(t2)
print('-' * 50)
print(t1 + t2)
print('-' * 50)
print(t1 * t2)  #是否是矩阵乘法？不是


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------------------------------------
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [ ]:
#shape不同，不能进行运算

In [27]:
#一维数组和二维数组进行运算时，一维的元素个数和列数相等
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print(t1)
print(t2)
t1 - t2

(1, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [28]:
(t1 - t2).shape

(4, 6)

In [29]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print(t1)
t1 - t2

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

# 练习轴

In [30]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 20)
print(np.sum(a, axis=0))  # [5 7 9]，按哪个轴求和，哪个轴没了
print("-" * 20)
print(np.sum(a, axis=1))  # [ 6 15]
print("-" * 20)
print(np.sum(a))

[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]
--------------------
21


In [31]:
a = np.arange(24).reshape((2, 3, 4))
b = np.sum(a, axis=0)
print("-" * 20)
print(b.shape)
c = np.sum(a, axis=1)
print("-" * 20)
print(c.shape)
d = np.sum(a, axis=2)
print("-" * 20)
print(d.shape)

--------------------
(3, 4)
--------------------
(2, 4)
--------------------
(2, 3)


# 索引和切片

In [32]:
a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2
# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[0], a)
# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])
#切片是左闭右开
print(a[2:8:2])

0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [33]:
t1 = np.arange(24).reshape(4, 6)
print(t1)
print('*' * 20)
print(t1[1])  # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*' * 20)
print(t1[1:])  # 取连续的多行
print('*' * 20)
print(t1[1:3, :])  # 取连续的多行
print('*' * 20)
print(t1[[0, 2, 3]])  # 取不连续的多行

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [34]:
print(t1[:, 1])  # 取一列
print('*' * 20)
print(t1[:, 1:])  # 连续的多列
print('*' * 20)
print(t1[:, [0, 2, 3]])  # 取不连续的多列
print('*' * 20)
print(t1[2, 3])  # # 取某一个值,三行四列  py是t1[2][3]
print('*' * 20)
print(t1[[0, 1, 1], [0, 1, 3]])  # 取多个不连续的值，[[行，行。。。],[列，列。。。]]

t1[1:3, 1:4]  #取1-3行，1-4列

[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************
[0 7 9]


array([[ 7,  8,  9],
       [13, 14, 15]])

# 修改值

In [35]:
t = np.arange(24).reshape(4, 6)
print(t)
print(id(t))
print('-' * 50)
# 修改某一行的值
t[1,:]=0

# 修改某一列的值
t[:,1]=0

# 修改连续多行
t[1:3,:]=0

# 修改连续多列
t[:,1:4]=0

# 修改多行多列，取第二行到第四行，第三列到第五列
t[1:3,2:5]=0

# 修改多个不相邻的点
t[[0,1],[1,3]]=0

# 可以根据条件修改，比如讲小于10的值改掉
t[t<10]=0

# 使用逻辑判断
t[(t>2)&(t<6)]=0	# 逻辑与，and
t[(t<2)|(t>6)]=0	# 逻辑或，or
t[~(t>6)]=0	# 逻辑非
print(t)
t = t.clip(10, 18)
print(id(t))
t

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
2508520970384
--------------------------------------------------
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
2508520972688


array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [36]:
t = np.arange(24).reshape(4, 6)
t < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [37]:
#python的三目运算
a = 10
b = 15
c = a if a > b else b
c

15