# numpy inf和nan

In [1]:
import numpy as np

In [2]:
# 创建一个nan和inf #
a = np.nan
b = np.inf
print(a, type(a))
print(b, type(b))

nan <class 'float'>
inf <class 'float'>


In [3]:
# np.nan != np.nan
print(np.nan == np.nan)
print(True == 1)
print(False == 0)
#nan和其他数运算的结果都是nan
np.nan + 1

False
True
True


nan

In [4]:
# 判断数组中为nan的个数
t = np.arange(24, dtype=float).reshape(4, 6)
# 将三行四列的数改成nan
t[3, 4] = np.nan
t[2, 4] = np.nan
print(t)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]


In [5]:
# 使用np.count_nonzero() 来判断非零的个数
print(np.count_nonzero(t))
print(t != t)
print('-' * 50)
# 统计nan的个数
print(np.count_nonzero(t != t))

23
[[False False False False False False]
 [False False False False False False]
 [False False False False  True False]
 [False False False False  True False]]
--------------------------------------------------
2


In [6]:
# 将nan替换为0
t[np.isnan(t)] = 0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [18]:
# 处理数组中nan
t = np.arange(24).reshape(4, 6).astype('float')
# 将第3行2开始的元素变为nan
t[3, 2:] = np.nan
print(t)
print(t.shape)
print(id(t))
# t的列数
t.shape[1] 

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. nan nan nan nan]]
(4, 6)
2282877817008


6

In [19]:
# 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]):
    #获取当前列数据
    temp_col = t[:, i]

    # 判断当前列的数据中是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col)
    # 条件成立说明含有nan
    if nan_num != 0:
        # 将这一列不为nan的数据拿出来,并计算平均值
        temp_col_not_nan = temp_col[temp_col == temp_col]
        print(temp_col_not_nan)
        # 将nan替换成这一列的平均值
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
print('-'*50)
print(t)
print(id(t))

[ 2.  8. 14.]
[ 3.  9. 15.]
[ 4. 10. 16.]
[ 5. 11. 17.]
--------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19.  8.  9. 10. 11.]]
2282877817008


In [20]:
# np.nan和任何数据运算的结果都是nan
t = np.arange(24).reshape(4, 6).astype('float')
#
# 将数组中的一部分替换nan
t[1, 3:] = np.nan

t1 = np.arange(24).reshape(4, 6).astype('float')
t + t1

array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., nan, nan, nan],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]])

In [21]:
# 1除0就会得到inf
arr = np.array([-1, 0])
print(arr)
print(arr[0] / arr[1])

[-1  0]
-inf


C:\Users\ArkhamCraft\AppData\Local\Temp\ipykernel_28624\4034376636.py:4: RuntimeWarning: divide by zero encountered in scalar divide
  print(arr[0] / arr[1])


In [22]:
# nan和任何数相加都是nan
np.nan + np.inf

nan