# 转置和轴滚动

In [1]:
import numpy as np

In [6]:
#对换数组的维度
a = np.arange(12).reshape(3, 4)
print('原数组：')
print(a)
print(a.shape)
print('\n')

print('对换数组：')
print(np.transpose(a))
print(np.transpose(a).shape)
print('\n')

# 与transpose一致
a = np.arange(12).reshape(3, 4)

print('原数组：')
print(a)
print('\n')

print('转置数组：')
print(a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [8]:
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4, 6)
# 交换了0轴和1轴
re1 = t1.swapaxes(1, 0)

print(' 原 数 组 ：')
print(t1)
print(t1.shape)
print('\n')
print(re1.shape)
print('调用 swapaxes 函数后的数组：')
print(re1)

 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


(6, 4)
调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [11]:
#如果是3维及以上，称为轴交换
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print('-' * 50)
# 交换了1轴和2轴
t3 = np.swapaxes(t3, 1, 2)
print(t3.shape)

(3, 4, 5)
--------------------------------------------------
(3, 5, 4)


In [15]:
# 数组的轴滚动
a = np.ones((3, 4, 5, 6))
print(a.shape)
b = np.rollaxis(a, 3, 1)
print(b.shape)

(3, 4, 5, 6)
(3, 6, 4, 5)


In [16]:
print(b.shape)
#轴会滚动，直到它位于此位置之前
c=np.rollaxis(b, 1,4) 
print(c.shape)

(3, 6, 4, 5)
(3, 4, 5, 6)


In [18]:
#数据拷贝，copy()和赋值的区别
# copy不改变原来的
b = np.array([[1, 2, 3], [1, 2, 3]])
a = b.copy()
a
b[0, 0] = 3
print(b)
a

[[3 2 3]
 [1 2 3]]


array([[1, 2, 3],
       [1, 2, 3]])